CREATE DATABASE CAMPEONATO_AMADOR;
GO

USE CAMPEONATO_AMADOR;
GO

CREATE TABLE [TIME]
(
    ID                      INT                  NOT NULL
    ,NOME                    VARCHAR(50)         NOT NULL
    ,APELIDO                 VARCHAR(30)         NOT NULL
    ,DATA_CRIACAO            DATE                NOT NULL

    CONSTRAINT PK_TIME_ID                       PRIMARY KEY (ID)
);
GO

CREATE TABLE [CAMPEONATO]
(
    ID_CAMPEONATO           INT                  NOT NULL
    ,ANO                     INT                 NOT NULL
    ,NOME                    VARCHAR(50)         NOT NULL

    CONSTRAINT PK_CAMPEONATO_ID                 PRIMARY KEY (ID_CAMPEONATO)
);
GO

CREATE TABLE [JOGO]
(
    ID_JOGO                  INT                  NOT NULL
    ,TIME_CASA_ID            INT                 NOT NULL
    ,TIME_VISITANTE_ID       INT                 NOT NULL
    ,GOL_CASA                INT                 DEFAULT 0
    ,GOL_VISITANTE           INT                 DEFAULT 0
    ,GOLS_JOGO               INT                 DEFAULT 0     

    CONSTRAINT PK_JOGO_ID                    PRIMARY KEY (ID_JOGO)
    ,CONSTRAINT FK_TIME_CASA_ID_TIME         FOREIGN KEY (TIME_CASA_ID)             REFERENCES [TIME] (ID)
    ,CONSTRAINT FK_TIME_VISITANTE_ID_TIME    FOREIGN KEY (TIME_VISITANTE_ID)        REFERENCES [TIME] (ID)
);
GO

CREATE TABLE [GOLS_TIME]
(
    TIME_ID                  INT                 NOT NULL
    ,GOLS_MARCADOS           INT                 DEFAULT 0
    ,GOLS_SOFRIDOS           INT                 DEFAULT 0
    ,PONTUACAO               INT                 DEFAULT 0

    CONSTRAINT PK_TIME_GOLS_TIME                 PRIMARY KEY (TIME_ID)
    ,CONSTRAINT FK_TIME_GOLS_TIME                FOREIGN KEY (TIME_ID)           REFERENCES [TIME] (ID)
);
GO

-- PROCEDURE POPULANDO TIMES
EXEC.CADASTRA_TIME;
GO

--PROCEDURE POPULANDO CAMPEONATO 5BY5
EXEC.CRIA_CAMPEONATO;
GO

--MOCKANDO JOGOS
EXEC.JOGAR_JOGOS;
GO

--PREENCHENDO TABELA COM GOLS E PONTUAÇÃO
EXEC.PREENCHE_GOLS_TIME;
GO



--SELECTS
SELECT * FROM [TIME]
SELECT * FROM [CAMPEONATO]
SELECT * FROM [JOGO]
SELECT * FROM [GOLS_TIME]



-- Campeão por pontos
SELECT TOP 1 T.NOME, GT.PONTUACAO 
FROM [TIME] T 
INNER JOIN [GOLS_TIME] GT ON T.ID = GT.TIME_ID
ORDER BY GT.PONTUACAO DESC



-- TOP 3
SELECT TOP 3 T.NOME, GT.PONTUACAO 
FROM [TIME] T 
INNER JOIN [GOLS_TIME] GT ON T.ID = GT.TIME_ID
ORDER BY GT.PONTUACAO DESC, GT.GOLS_MARCADOS

--Time com mais gols
SELECT TOP 1 T.NOME, GT.GOLS_MARCADOS
FROM [TIME] T 
INNER JOIN [GOLS_TIME] GT ON T.ID = GT.TIME_ID
ORDER BY GT.GOLS_MARCADOS DESC

--Time mais Frango
SELECT TOP 1 T.NOME, GT.GOLS_SOFRIDOS
FROM [TIME] T 
INNER JOIN [GOLS_TIME] GT ON T.ID = GT.TIME_ID
ORDER BY GT.GOLS_SOFRIDOS DESC

--JOgo com mais gols
SELECT TOP 1 J.ID_JOGO, T1.NOME AS TIME_CASA, T2.NOME AS TIME_VISITANTE, J.GOL_CASA + J.GOL_VISITANTE AS TOTAL_DE_GOLS
FROM [JOGO] J
JOIN [TIME] T1 ON J.TIME_CASA_ID = T1.ID
JOIN [TIME] T2 ON J.TIME_VISITANTE_ID = T2.ID
ORDER BY J.GOLS_JOGO DESC

--Rnk de Gols
SELECT TOP 3 J.ID_JOGO, T1.NOME AS TIME_CASA, T2.NOME AS TIME_VISITANTE, J.GOL_CASA + J.GOL_VISITANTE AS TOTAL_DE_GOLS
FROM [JOGO] J
INNER JOIN [TIME] T1 ON J.TIME_CASA_ID = T1.ID
INNER JOIN [TIME] T2 ON J.TIME_VISITANTE_ID = T2.ID
ORDER BY J.GOLS_JOGO DESC

--Maximo de Gols por jogo
SELECT
  TIME.NOME AS TIME, 
  MAX(JOGO.GOL_CASA) AS MAXIMO_GOLS_EM_CASA, 
  MAX(JOGO.GOL_VISITANTE) AS MAXIMO_GOLS_FORA
FROM 
  [JOGO] 
  JOIN [TIME] ON [TIME].ID = JOGO.TIME_CASA_ID OR TIME.ID = JOGO.TIME_VISITANTE_ID 
GROUP BY 
  TIME.NOME;

--DROP PROC PREENCHE_GOLS_TIME

--DROP TABLE [JOGO]
--DROP TABLE [GOLS_TIME]
--DROP TABLE [CAMPEONATO]
--DROP TABLE [TIME]

--DELETE [JOGO]